In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'1.10.0'

In [3]:
hello  = tf.constant("Hello")

In [4]:
world = tf.constant('World')

In [5]:
type(world)

tensorflow.python.framework.ops.Tensor

In [6]:
hello

<tf.Tensor 'Const:0' shape=() dtype=string>

In [7]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [11]:
with tf.Session() as s:
    result = s.run(hello+world)

In [12]:
result

b'HelloWorld'

In [13]:
a = tf.constant(10)
b = tf.constant(20)

In [14]:
with tf.Session() as s:
    result = s.run(a+b)

In [15]:
result

30

In [16]:
const = tf.constant(10)

In [18]:
fill_mat = tf.fill((4,4),10)

In [31]:
myzeros = tf.zeros((4,4))

In [30]:
myones = tf.ones((4,4))

In [22]:
myrandn = tf.random_normal((4,4))

In [23]:
myrandu = tf.random_uniform((4,4))

In [33]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [25]:
s = tf.InteractiveSession()

In [34]:
for op in my_ops:
    print(s.run(op))
    print('\n\n')

10



[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]



[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]



[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]



[[-0.73652434  0.662257    0.24695757  0.407117  ]
 [ 1.6424782   0.02632575  0.8835176   0.7234919 ]
 [ 2.111267   -0.52267295 -0.40427446  0.5958962 ]
 [-0.32108074 -0.36937088  1.6515279   0.195359  ]]



[[0.03344285 0.84709    0.90560865 0.96508384]
 [0.577665   0.7250246  0.9456614  0.45700145]
 [0.19831336 0.7997577  0.0358125  0.6495228 ]
 [0.6461475  0.61035275 0.6836152  0.6816162 ]]





In [41]:
a = tf.constant([[1,2],[3,4]])

In [42]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [47]:
b = tf.constant([[10],[100]])

In [48]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [49]:
result = a * b

In [50]:
s.run(result)

array([[ 10,  20],
       [300, 400]], dtype=int32)

In [51]:
res = tf.matmul(a,b)

In [52]:
s.run(res)

array([[210],
       [430]], dtype=int32)

In [53]:
mlt = tf.multiply(a,b)

In [54]:
s.run(mlt)

array([[ 10,  20],
       [300, 400]], dtype=int32)